export const APP_ACTIONS = {
  RESET_PRODUCTS: 'RESET_PRODUCTS',
  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_PRODUCT: 'SET_PRODUCT',
  UPDATE_PRODUCT_CART: 'UPDATE_PRODUCT_CART'
}

export default { APP_ACTIONS }
